### PR TITLE
Fix h2 test

### LINKED ISSUE #223: Tests no longer send 2FA push notifications.
Likely due to changes in #221 

Test eventually fails with:
```
Failures:

  1) Create a new ETD is expected to have text "Could not find an Etd with id: 0001"
     Failure/Error: expect(page).to have_content expected_text
       expected to find text "Could not find an Etd with id: 0001" in "Two-step authentication is required to log in\nImportant Security Information: Logging in lets you access other protected Stanford websites with this browser, not just the website you requested.\nLOGIN HELP\nTWO-STEP HELP\nTWO-STEP DEVICE UNAVAILABLE?\nUse of this system is subject to Stanford University's rules and regulations. See the Stanford Administrative Guide for more information.\nSU Home Maps & Directions Search Stanford Terms of Use Emergency Info\n© Stanford University.  Stanford, California 94305. Copyright Complaints   Trademark Notice"
     # ./spec/support/authentication_helpers.rb:14:in `block in authenticate!'
     # ./spec/support/authentication_helpers.rb:12:in `authenticate!'
     # ./spec/features/create_etd_spec.rb:73:in `block (2 levels) in <top (required)>'
```

### LINKED ISSUE #224: feature flag for automatic authentication
PR #221  allowed me to run the hydrus integration test, but slowed down integration tests for JCoyne.  This ticket is to put the code I need behind a feature flag, so the tests can be easily used without slow downs by JCoyne and others with his authentication situation, and the same for moi.

### PR DESCRIPTION
**Pull request by ndushay**
## Why was this change made?

These tweaks get the h2 test to work with the changes to authentication from PR #221, and get the hydrus test to work with the indexing changes in PR sul-dlss/dor_indexing_app/pull/580.

I was able to get each of the tests to run green in stage with these changes.

Part of fixing sul-dlss/infrastructure-integration-test/issues/219

FIxes #224 
Fixes #223

### CODE REVIEW

**Comment by jcoyne** [comment]
I tried this and the h2 test now takes 100 seconds longer to run than it used to.

File: spec/features/deposit_via_hydrus_spec.rb [hunk 1]
```diff
@@ -78,7 +78,7 @@
     visit "#{Settings.argo_url}/view/#{item_druid}"
 
     # page does not initially display title, loop until reindexed
-    reload_page_until_timeout!(text: "Stanford, Jane Lathrop #{item_title}: 2000-01-01")
+    reload_page_until_timeout!(text: "Stanford, Jane Lathrop #{item_title}: 2000")
```
Comment (jcoyne) [inline spec/features/deposit_via_hydrus_spec.rb:81]: Was the prior expectation wrong or are we changing the tests to expect the wrong behavior that we currently have?

Comment (ndushay) [reply spec/features/deposit_via_hydrus_spec.rb:81]: the pub date coming from stanford-mods was year only;  this is NOT that field, so I can undo this change!  Thanks for spotting.

Comment (ndushay) [reply spec/features/deposit_via_hydrus_spec.rb]: @jcoyne ok, reverted this change to match the dor-indexing-app.  :-)

**Comment by ndushay** [comment]
As to the time to run tests -- I couldn't run the hydrus test at all without the changes in PR #221 -- I wonder if the wait times can be dialed down.

It was impossible for me to test all the case in #221 - no one of us will be able to do so.  I'm not sure what is going on or how to make it better ...

a slow test that works is better than a test that always fails???

**Comment by jcoyne** [comment]
How about we have a feature flag for the strategy for dealing with DUO?

**Comment by ndushay** [comment]
feature flag is a good idea.   I'll make a ticket and work on it.  I theoretically signed up for CardinalKey - could that be the difference?

**Comment by ndushay** [comment]
In any case, we're discussing a problem from an older, merged PR ... not related to the changes in _this_ PR ... so maybe this could be merged while I work on the feature flag pertaining to #221 changes?

File: spec/features/create_object_h2_spec.rb [hunk 2]
```diff
@@ -5,13 +5,12 @@
...
-    click_link 'Start here'
-    submit_credentials
-
-    click_button 'No' if has_content? 'Continue your deposit'
+  before do
+    authenticate!(start_url: "#{Settings.h2_url}/dashboard", expected_text: 'Create a new collection')
+  end
 
+  scenario do
+    click_button 'No' if page.has_content?('Continue your deposit', wait: 100)
```
Comment (ndushay) [inline spec/features/create_object_h2_spec.rb:13]: I think the wait time culprit is THIS one.  Fixing.

**Review by jcoyne — APPROVED** [review]

**Review by jermnelson — APPROVED** [review]
