### PR TITLE
etd spec waits for submit-marc and check-marc steps to complete

### LINKED ISSUE #619: etd test needs to wait for submit-marc and catalog-status steps to complete
ETD test fails when it is checking Argo workflow modal for folio steps that take a bit to run.

Ideally, ETD test would have a loop that:

- opens ETD workflow and looks for all steps through check-marc completed
   - if completed, we're done, break out of loop and move on
   - if not completed, cancel out of the workflow modal, then load it again
 
Dirty fix is just to wait long enough before checking

### PR DESCRIPTION
**Pull request by ndushay**
## Why was this change made? 🤔

Fixes #619

For me, on a fast fiber connection, checking the ETD workflow in argo was happening before the submit-marc and check-marc etdSubmitWF steps were completed, so the test would fail.   This PR fixes that problem.

## Was README.md updated if necessary? 🤨

no need.

### CODE REVIEW

File: spec/features/etd_creation_spec.rb [hunk 1]
```diff
@@ -216,40 +216,32 @@
     expect(apo_element.first('a')[:href]).to end_with('druid:bx911tp9024') # this is hardcoded in hydra_etd app
     status_element = find_table_cell_following(header_text: 'Status')
     expect(status_element).to have_text('v1 Registered')
-    if Settings.folio.enabled
```
Comment (ndushay) [inline spec/features/etd_creation_spec.rb:219]: since I was already making changes right here, I just yanked the folio switch out.

File: spec/features/etd_creation_spec.rb [hunk 2]
```diff
@@ -216,40 +216,32 @@
...
-        expect(page).to have_text(/reader-approval completed/)
-        expect(page).to have_text(/registrar-approval completed/)
-        expect(page).to have_text(/submit-marc completed/)
-        expect(page).to have_text(/check-marc waiting/)
-
-        # NOTE: it would be lovely if we could process the ETD through the rest of the etdSubmitWF steps
-        #   and then run it through common-accessioning, but the remaining etdSubmitWF steps of check-marc,
-        #   catalog-status, and otherMetadata require too much fakery specific to the ETD app (cocina-model
-        #   updates) to make sense here.
+        within('.modal-dialog') do
```
Comment (ndushay) [inline spec/features/etd_creation_spec.rb:224]: because this is a timeout loop that has to look at a modal, it didn't seem worth it to generalize this situation.  Perhaps that will change in the future.  For now, I made it bespoke to ETDs.

File: spec/features/etd_creation_spec.rb [hunk 3]
```diff
@@ -216,40 +216,32 @@
...
+            page.has_text?(/submit-marc\s+completed/, wait: 1) &&
+            page.has_text?(/check-marc\s+completed/, wait: 1) &&
+            page.has_text?(/catalog-status\s+waiting/, wait: 1)
+
+          # NOTE: it would be lovely if we could process the ETD through the rest of the etdSubmitWF steps
+          #   and then run it through common-accessioning, but the remaining etdSubmitWF steps, catalog-status and
+          #   otherMetadata, require too much fakery specific to the ETD app (cron job, cocina-model updates)
+          #   to make sense here.
+
+          page.send_keys(:escape)
```
Comment (ndushay) [inline spec/features/etd_creation_spec.rb:239]: it turns out that "Cancel" is not unique on the page and we don't have identifiers or other unique selectors on these blacklight modal buttons.  So I opted to go with the escape key to close the modal.

File: spec/features/etd_creation_spec.rb [hunk 4]
```diff
@@ -216,40 +216,32 @@
     expect(apo_element.first('a')[:href]).to end_with('druid:bx911tp9024') # this is hardcoded in hydra_etd app
     status_element = find_table_cell_following(header_text: 'Status')
     expect(status_element).to have_text('v1 Registered')
-    if Settings.folio.enabled
-      reload_page_until_timeout! do
+
+    Timeout.timeout(Settings.timeouts.workflow) do
+      workflow_done = false
```
Comment (ndushay) [inline spec/features/etd_creation_spec.rb:221]: this is clunky, but apparently "break" only gets out of the "within" and we needed to get out of both the "within" and the "loop" statement.

**Review by mjgiarlo — APPROVED** [review]
